import { Wallet } from "ethers";
import * as fs from "fs";
import * as path from "path";

/**
 * Creates .env.kairos with 13 fresh testnet-only keys (deployer, city, bank, oracle, attester,
 * 5 payers, 3 merchants). Does nothing when the file already exists. Prints addresses only.
 */
const ENV_PATH = path.resolve(__dirname, "..", "..", ".env.kairos");

function main() {
  if (fs.existsSync(ENV_PATH)) {
    console.log(`${ENV_PATH} already exists; nothing to do (delete it to regenerate)`);
    return;
  }
  const roles = ["DEPLOYER_KEY", "CITY_KEY", "BANK_KEY", "ORACLE_KEY", "ATTESTER_KEY"];
  const single = roles.map((r) => [r, Wallet.createRandom()] as const);
  const payers = Array.from({ length: 5 }, () => Wallet.createRandom());
  const merchants = Array.from({ length: 3 }, () => Wallet.createRandom());

  const lines = [
    "# Kaia Kairos testnet keys. TESTNET ONLY, generated by scripts/gen-keys.ts. Never commit.",
    "RPC_URL=https://public-en-kairos.node.kaia.io",
    "CHAIN_ID=1001",
    ...single.map(([r, w]) => `${r}=${w.privateKey}`),
    `PAYER_KEYS=${payers.map((w) => w.privateKey).join(",")}`,
    `MERCHANT_KEYS=${merchants.map((w) => w.privateKey).join(",")}`,
    "ENGINE_URL=http://127.0.0.1:8000",
    "PENDING_DELAY=60",
    "CAPS_DELAY=60",
    "KAIROS_RPC_URL=https://public-en-kairos.node.kaia.io",
    "DB_PATH=./engine/engine.kairos.db",
    "WEB_ORIGIN=http://localhost:3000",
    "PORT=8000",
    "",
  ];
  fs.writeFileSync(ENV_PATH, lines.join("\n"), { mode: 0o600 });
  fs.chmodSync(ENV_PATH, 0o600);

  console.log(`wrote ${ENV_PATH} (mode 600). Addresses:`);
  const rows: Array<[string, string]> = [
    ...single.map(([r, w]) => [r.replace("_KEY", "").toLowerCase(), w.address] as [string, string]),
    ...payers.map((w, i) => [`payer ${i + 1}`, w.address] as [string, string]),
    ...merchants.map((w, i) => [`merchant ${i + 1}`, w.address] as [string, string]),
  ];
  for (const [role, address] of rows) console.log(`  ${role.padEnd(12)} ${address}`);
  console.log(`\nfund the deployer with test KAIA: https://faucet.kaia.io -> ${single[0][1].address}`);
}

main();
